# Generated by Django 6.0.1 on 2026-02-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addimage',
            name='title',
            field=models.CharField(default='Untitled', max_length=400),
        ),
    ]
