# Generated by Django 6.0.1 on 2026-02-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_images_list'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images_list',
        ),
        migrations.AddField(
            model_name='addimage',
            name='des',
            field=models.CharField(default='Untitled', max_length=2000),
        ),
    ]
