# Generated by Django 6.0.1 on 2026-02-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_delete_images_list_addimage_des'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
